### ISSUE TITLE
Support for complex modulations

### ISSUE THREAD

**Issue by kagel** [alecominotti/hydracodegenerator#1]
Any plans to add support for nested modulations?

like this:
```
s1.initImage(
  "https://upload.wikimedia.org/wikipedia/commons/2/25/Hydra-Foto.jpg"
);
noise()
  .modulateRepeatY(
    src(s1)
      .modulateKaleid(
        noise()
          .modulateKaleid(
            voronoi().colorama().scale()
          )
          .modulate(solid().luma().repeatY())
      )
      .scrollY()
  )
  .diff(voronoi().scrollX().color())
  .out();

```

**Comment by alecominotti** [comment]
Hi @kagel , nested modulations have been considered but not implemented yet, to not make the code too complex to control the desired amount of functions

**Comment by kagel** [comment]
> Hi @kagel , nested modulations have been considered but not implemented yet, to not make the code too complex to control the desired amount of functions

thanks
